name: Test plugin

on:
  schedule:
    # runs once a week
    # - cron: '0 6 * * 0'
    # runs every day
    - cron: '0 12 * * *'
  push:
    branches: [ "master", "try_ci-1" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Pull qgis image
      run: docker pull qgis/qgis:stable

    - name: Pip install
      run: docker run --name qgis_container --volume $(pwd):/app -w=/app qgis/qgis:stable sh -c "python3 -m pip install -r requirements_dev.txt --break-system-packages"

    - name: Run tests
      run: docker start qgis_container && docker exec qgis_container sh -c "xvfb-run -s '+extension GLX -screen 0 1024x768x24' python3 -m pytest tests -s"
